# Generated by Django 4.2.5 on 2023-09-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simg',
            name='detected',
        ),
        migrations.CreateModel(
            name='DImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detect', models.FileField(upload_to='detect/')),
                ('img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.simg')),
            ],
        ),
    ]
