# Generated by Django 4.2.5 on 2023-09-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_simg_detected_dimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimg',
            name='img',
        ),
    ]
