# Generated by Django 4.2.5 on 2023-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_dimg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimg',
            name='detect',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
